### ISSUE TITLE
While installing can't start FulcrumWatchdogService.exe

### ISSUE THREAD

**Issue by Upgreydd** [MEAT-Inc/Fulcrum#322]
Installation fails at latest release due to FulcrumWatchdogService.exe start problem

**Comment by ZacharyWalsh57** [comment]
Issue resolved. During install, the watchdog was trying to boot a monitor for the C:\DrewTech\Logs folder but was not found on client machines. Updated watchdog service to build watched folders on startup if the paths requested do not exist.
